### ISSUE TITLE
process, vmem and rss overreporting

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo-collectors#2]
In multi-process and multi-threaded process aggregation it is common for the same library to loaded into memory and shared read-only across multiple threads/process, this also goes for shared stack.

In the current process script smaps is checked but memory address are not de-deuped across multiple processes.

To de-dupe memory addresses, one would only need to match, address, offset, dev, and inode across multiple child processes. 

Taken from `man proc`

```
address           perms offset  dev   inode       pathname
35b1800000-35b1820000 r-xp    00000000 08:02 135522  /usr/lib64/ld-2.15.so
```

**Comment by jhunt** [comment]
Any update on this?

**Comment by GrayTShirt** [comment]
I've double checked the data over the last 20 months, I'm going to close this as this isn't the case
